// The giveaway. Higgsfield's "moat" is this list surfaced as clickable buttons.
// Here it's plain data — MIT, extend freely. Model-agnostic cinematography prose.

import type { Preset } from "./types.js";

export const CAMERA_PRESETS: Preset[] = [
  {
    id: "dolly-in",
    label: "Dolly In",
    category: "camera",
    desc: "Camera glides straight toward the subject, closing distance.",
    template: "the camera slowly dollies in toward {subject}, smooth forward push, steady tracking, cinematic depth",
    params: { camera_motion: "dolly_in" },
    tags: ["push", "approach", "forward"],
  },
  {
    id: "dolly-out",
    label: "Dolly Out",
    category: "camera",
    desc: "Camera pulls back to reveal the wider scene.",
    template: "the camera slowly dollies out away from {subject}, smooth backward pull revealing the surroundings, cinematic reveal",
    params: { camera_motion: "dolly_out" },
    tags: ["pull", "reveal", "backward"],
  },
  {
    id: "crane-up",
    label: "Crane Up",
    category: "camera",
    desc: "Camera booms upward over the subject, rising vertical move.",
    template: "the camera cranes upward over {subject}, rising boom shot, sweeping vertical ascent, epic scale",
    params: { camera_motion: "crane_up" },
    tags: ["boom", "rise", "vertical"],
  },
  {
    id: "orbit",
    label: "Orbit / Arc",
    category: "camera",
    desc: "Camera circles around the subject in a smooth arc.",
    template: "the camera orbits smoothly around {subject} in a 180-degree arc, subject stays centered, parallax reveals depth",
    params: { camera_motion: "orbit" },
    tags: ["arc", "circle", "rotate", "360"],
  },
  {
    id: "tracking",
    label: "Tracking Shot",
    category: "camera",
    desc: "Camera follows alongside the moving subject.",
    template: "a tracking shot following {subject} in motion, camera moves parallel keeping pace, steadicam smoothness",
    params: { camera_motion: "tracking" },
    tags: ["follow", "steadicam", "side"],
  },
  {
    id: "whip-pan",
    label: "Whip Pan",
    category: "camera",
    desc: "Fast blurred pan snapping to the subject.",
    template: "a fast whip pan snapping onto {subject}, motion-blurred sweep, energetic transition, sudden focus",
    params: { camera_motion: "whip_pan" },
    tags: ["fast", "snap", "blur", "transition"],
  },
  {
    id: "bullet-time",
    label: "Bullet Time",
    category: "camera",
    desc: "Time freezes while the camera arcs around the subject.",
    template: "bullet time effect around {subject}, action frozen mid-motion while the camera arcs around, dramatic slow-motion, 360 sweep",
    params: { camera_motion: "orbit", speed: "slow" },
    tags: ["matrix", "freeze", "slowmo"],
  },
  {
    id: "crash-zoom",
    label: "Crash Zoom",
    category: "camera",
    desc: "Sudden aggressive zoom onto the subject.",
    template: "a sudden crash zoom into {subject}, rapid aggressive push, snap emphasis, punchy energy",
    params: { camera_motion: "zoom_in", speed: "fast" },
    tags: ["snap-zoom", "punch", "fast"],
  },
  {
    id: "fpv-drone",
    label: "FPV Drone",
    category: "camera",
    desc: "Fast first-person drone flythrough.",
    template: "an FPV drone shot racing toward and past {subject}, fast dynamic flight, sweeping banked turns, immersive first-person motion",
    params: { camera_motion: "fpv" },
    tags: ["drone", "fly", "fpv", "fast"],
  },
  {
    id: "snorricam",
    label: "Snorricam",
    category: "camera",
    desc: "Camera rigged to the subject; background swings around them.",
    template: "a snorricam shot locked to {subject}, subject stays fixed and centered while the background swings and moves around them, disorienting energy",
    params: { camera_motion: "locked_subject" },
    tags: ["rig", "body-mount", "disorient"],
  },
  {
    id: "low-angle-hero",
    label: "Low Angle Hero",
    category: "camera",
    desc: "Looking up at the subject for power and scale.",
    template: "a low-angle hero shot looking up at {subject}, towering imposing framing, dramatic scale, powerful stance",
    params: { camera_motion: "static", angle: "low" },
    tags: ["heroic", "power", "up"],
  },
  {
    id: "handheld",
    label: "Handheld",
    category: "camera",
    desc: "Raw handheld shake for documentary realism.",
    template: "a handheld shot of {subject}, subtle organic camera shake, documentary realism, run-and-gun energy",
    params: { camera_motion: "handheld" },
    tags: ["shaky", "docu", "raw", "realism"],
  },
];
