// Lens / optics presets. Simulate real glass — focal length, aperture, format.
import type { Preset } from "./types.js";

export const LENS_PRESETS: Preset[] = [
  {
    id: "wide-14mm",
    label: "Ultra-Wide 14mm",
    category: "lens",
    desc: "Sweeping ultra-wide field, exaggerated depth.",
    template: "shot on a 14mm ultra-wide lens, expansive field of view, exaggerated perspective and depth, edge stretch",
    params: { focal_length_mm: 14 },
    tags: ["wide", "expansive", "landscape"],
  },
  {
    id: "portrait-85mm",
    label: "Portrait 85mm",
    category: "lens",
    desc: "Flattering compression, creamy background separation.",
    template: "shot on an 85mm portrait lens, flattering facial compression, shallow depth of field, creamy bokeh separating subject from background",
    params: { focal_length_mm: 85, aperture: "f/1.4" },
    tags: ["portrait", "bokeh", "compression"],
  },
  {
    id: "macro",
    label: "Macro",
    category: "lens",
    desc: "Extreme close-up, tiny details huge.",
    template: "extreme macro shot, razor-thin plane of focus, intricate surface detail magnified, soft falloff",
    params: { focal_length_mm: 100, aperture: "f/2.8" },
    tags: ["closeup", "detail", "tiny"],
  },
  {
    id: "anamorphic",
    label: "Anamorphic",
    category: "lens",
    desc: "Cinemascope squeeze, horizontal flares, oval bokeh.",
    template: "shot on anamorphic lenses, 2.39:1 cinemascope framing, horizontal blue lens flares, oval bokeh, filmic squeeze",
    params: { aspect_ratio: "2.39:1", flare: "anamorphic" },
    tags: ["cinemascope", "flare", "widescreen", "film"],
  },
  {
    id: "tilt-shift",
    label: "Tilt-Shift",
    category: "lens",
    desc: "Miniature-faking selective focus plane.",
    template: "tilt-shift lens effect, narrow tilted plane of focus, miniature-model look, selective sharpness",
    params: { effect: "tilt_shift" },
    tags: ["miniature", "diorama", "selective"],
  },
  {
    id: "fisheye",
    label: "Fisheye",
    category: "lens",
    desc: "Extreme barrel distortion, 180-degree bulge.",
    template: "fisheye lens, extreme barrel distortion, 180-degree bulging field of view, curved horizon",
    params: { focal_length_mm: 8, distortion: "barrel" },
    tags: ["distort", "skate", "bulge"],
  },
  {
    id: "shallow-dof",
    label: "Shallow Depth of Field",
    category: "lens",
    desc: "Wide-open aperture, subject pops from blur.",
    template: "very shallow depth of field, wide-open aperture, subject in crisp focus against a soft dreamy blur",
    params: { aperture: "f/1.2" },
    tags: ["bokeh", "blur", "focus"],
  },
  {
    id: "deep-focus",
    label: "Deep Focus",
    category: "lens",
    desc: "Everything sharp foreground to background.",
    template: "deep focus, everything from foreground to distant background rendered sharp, large depth of field",
    params: { aperture: "f/16" },
    tags: ["sharp", "everything", "landscape"],
  },
];
