// Style / look presets. Film stocks, eras, genres, mediums.
import type { Preset } from "./types.js";

export const STYLE_PRESETS: Preset[] = [
  {
    id: "35mm-film",
    label: "35mm Film",
    category: "style",
    desc: "Analog grain, halation, organic color.",
    template: "shot on 35mm film, fine organic grain, subtle halation on highlights, rich filmic color, analog texture",
    tags: ["analog", "grain", "kodak", "celluloid"],
  },
  {
    id: "16mm-doc",
    label: "16mm Documentary",
    category: "style",
    desc: "Grainy handheld verite realism.",
    template: "shot on grainy 16mm film, documentary realism, slightly desaturated, vintage verite texture",
    tags: ["grain", "vintage", "verite", "retro"],
  },
  {
    id: "vhs",
    label: "VHS",
    category: "style",
    desc: "Lo-fi tape artifacts, scan lines, chroma bleed.",
    template: "VHS home-video aesthetic, soft lo-fi tape texture, scan lines, chroma bleed, tracking artifacts, retro 80s look",
    tags: ["retro", "80s", "lofi", "tape", "analog"],
  },
  {
    id: "teal-orange",
    label: "Teal & Orange",
    category: "style",
    desc: "Blockbuster complementary grade.",
    template: "cinematic teal and orange color grade, warm skin tones against cool teal shadows, glossy blockbuster look",
    tags: ["blockbuster", "grade", "hollywood", "contrast"],
  },
  {
    id: "bleach-bypass",
    label: "Bleach Bypass",
    category: "style",
    desc: "Desaturated, crushed, metallic contrast.",
    template: "bleach bypass color treatment, desaturated palette, crushed blacks, harsh metallic contrast, gritty war-film look",
    tags: ["gritty", "desaturated", "war", "harsh"],
  },
  {
    id: "anime",
    label: "Anime",
    category: "style",
    desc: "2D cel-shaded Japanese animation.",
    template: "Japanese anime style, hand-drawn cel-shaded 2D animation, expressive linework, vibrant flat color, dramatic speed lines",
    tags: ["2d", "cartoon", "cel", "manga"],
  },
  {
    id: "claymation",
    label: "Claymation",
    category: "style",
    desc: "Stop-motion clay with fingerprint texture.",
    template: "claymation stop-motion style, sculpted clay characters with visible fingerprint texture, handmade tactile look, subtle frame stepping",
    tags: ["stopmotion", "clay", "handmade", "aardman"],
  },
  {
    id: "3d-pixar",
    label: "3D Animated",
    category: "style",
    desc: "Glossy stylized 3D feature look.",
    template: "polished 3D animated feature film style, stylized character design, soft global illumination, glossy appealing surfaces",
    tags: ["3d", "cgi", "pixar", "render"],
  },
  {
    id: "noir-bw",
    label: "Film Noir B&W",
    category: "style",
    desc: "High-contrast black and white, venetian shadows.",
    template: "classic film noir, high-contrast black and white, hard venetian-blind shadows, smoky atmosphere, 1940s crime-drama mood",
    tags: ["bw", "monochrome", "noir", "1940s"],
  },
  {
    id: "hyperreal",
    label: "Hyperreal",
    category: "style",
    desc: "Crisp modern high-fidelity realism.",
    template: "hyperrealistic, ultra-detailed, crisp modern digital cinematography, lifelike textures, high dynamic range",
    tags: ["realistic", "sharp", "detail", "hdr"],
  },
];
